### ISSUE TITLE
Android v2.4.1が起動しない問題

### ISSUE THREAD

**Issue by YumNumm** [EQMonitor/EQMonitor#660]
## 概要
- 17:41に公開したv2.4.1から起動しない報告が相次いでいる
  - Firebase Crashlytics, Play Console上ではクラッシュが記録されていない
  - 原因不明

**Comment by YumNumm** [comment]
cf. https://x.com/yumnumm/status/1781642550555836856?s=46
↑の引用およびリプ

**Comment by YumNumm** [comment]
Flutter側というよりネイティブ側でクラッシュしていそうではある
- Gradle周りを更新したのでそれかも
- バージョン表記を vx.y.z.r から vx.y.z に変えたのでそれかも
- クラッシュが記録されていないのでもっと根本的な話かも
  - とりあえず log みないと話にならない
- 端末依存/機種依存の何かもなさそう
  - 100%再現していそう

**Comment by YumNumm** [comment]
あと20分くらいで家着きそう
着いたら速攻確認します

- Play Storeに特急審査はなさそう
  - リリース出しても待つしかない

**Comment by YumNumm** [comment]
確認すること
- PlayStoreからインストールして実行
  - logcatする
  - 原因判明すればOK
- しなかったらローカルビルドして実行
- それでも分からなかったらとりあえずGradle周りをRevert

**Comment by YumNumm** [comment]
対応
- [x] Androidユーザにクラッシュしている件について通知配信

**Comment by YumNumm** [comment]
30分経っても原因特定できなかったら v2.3.x をリリース

**Comment by YumNumm** [comment]
```
FATAL EXCEPTION: main
                                                                                                    Process: net.yumnumm.eqmonitor, PID: 29928
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{net.yumnumm.eqmonitor/net.yumnumm.eqmonitor.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/~~OAHPzLgtg02dIZ46UL076w==/net.yumnumm.eqmonitor-deYmUYLq6jGKsacUL4uqYA==/split_config.arm64_v8a.apk!/lib/arm64-v8a/libflutter.so" has bad ELF magic: 00000000
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4006)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4193)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:114)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2608)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8628)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
                                                                                                    Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/~~OAHPzLgtg02dIZ46UL076w==/net.yumnumm.eqmonitor-deYmUYLq6jGKsacUL4uqYA==/split_config.arm64_v8a.apk!/lib/arm64-v8a/libflutter.so" has bad ELF magic: 00000000
                                                                                                    	at r8.f.h(Unknown Source:509)
                                                                                                    	at io.flutter.embedding.engine.d.<init>(Unknown Source:35)
                                                                                                    	at io.flutter.embedding.android.d.I(Unknown Source:172)
                                                                                                    	at io.flutter.embedding.android.d.q(Unknown Source:7)
                                                                                                    	at io.flutter.embedding.android.c.onCreate(Unknown Source:13)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8980)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8958)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1526)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3988)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4193) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:114) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2608) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232) 
                                                                                                    	at android.os.Looper.loop(Looper.java:317) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8628) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878) 
                                                                                                    Caused by: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/~~OAHPzLgtg02dIZ46UL076w==/net.yumnumm.eqmonitor-deYmUYLq6jGKsacUL4uqYA==/split_config.arm64_v8a.apk!/lib/arm64-v8a/libflutter.so" has bad ELF magic: 00000000
                                                                                                    	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
                                                                                                    	at java.util.concurrent.FutureTask.get(FutureTask.java:191)
                                                                                                    	at r8.f.h(Unknown Source:29)
                                                                                                    	at io.flutter.embedding.engine.d.<init>(Unknown Source:35) 
                                                                                                    	at io.flutter.embedding.android.d.I(Unknown Source:172) 
                                                                                                    	at io.flutter.embedding.android.d.q(Unknown Source:7) 
                                                                                                    	at io.flutter.embedding.android.c.onCreate(Unknown Source:13) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8980) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8958) 
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1526) 
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3988) 
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4193) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:114) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2608) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232) 
                                                                                                    	at android.os.Looper.loop(Looper.java:317) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8628) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878) 
                                                                                                    Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/~~OAHPzLgtg02dIZ46UL076w==/net.yumnumm.eqmonitor-deYmUYLq6jGKsacUL4uqYA==/split_config.arm64_v8a.apk!/lib/arm64-v8a/libflutter.so" has bad ELF magic: 00000000
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1081)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1765)
                                                                                                    	at io.flutter.embedding.engine.FlutterJNI.loadLibrary(Unknown Source:13)
                                                                                                    	at r8.f$a.b(Unknown Source:19)
                                                                                                    	at r8.f$a.call(Unknown Source:0)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by YumNumm** [comment]
Gradle 部分をrevertして対応します

**Comment by YumNumm** [comment]
#662 において対応完了。
緊急対応で、`hotfix/android-crash`ブランチにおいて リリース実行。
審査提出済み

![image](https://github.com/YumNumm/EQMonitor/assets/73390859/2928d2ab-babd-4bfb-a8bd-f7d272554ce3)

**Comment by YumNumm** [comment]
影響ユーザ数と 直接原因・間接原因・対応についてまとめたい

**Comment by YumNumm** [comment]
現段階では、v2.4.1のインストール数不明
![image](https://github.com/YumNumm/EQMonitor/assets/73390859/14ce0978-56be-456b-b9eb-fefae51977ab)
